export const analyticsContent = {
  charts: {
    digitHeatmapTitle: "Digit heatmap",
    numberFrequencyTitle: "Top number frequency"
  },
  emptyState: {
    description: "Seed draw and prize records before enabling the production analytics view.",
    title: "No analytics records"
  },
  filterSummary:
    "Filters will be URL-backed in the next UI pass. This view currently uses the default analytics window contract.",
  hero: {
    description:
      "Historical draw data is grouped into digit and number statistics for analysis. These signals describe past behavior only.",
    eyebrow: "Analytics",
    title: "Frequency, position, and recency signals"
  },
  metrics: {
    digitGroups: "Digit groups",
    draws: {
      hint: "Distinct draw records included in this analytics response.",
      label: "Draws"
    },
    generated: "Generated",
    numberGroups: "Number groups",
    patterns: "Patterns",
    source: {
      hint: "Generated by API contract or fallback mock.",
      label: "Source"
    }
  },
  sample: {
    eyebrow: "Data window",
    title: "Current sample"
  },
  sections: {
    digitStats: {
      eyebrow: "Digit stats",
      title: "Position frequency"
    },
    numberStats: {
      eyebrow: "Number stats",
      tableHeaders: {
        frequency: "Frequency",
        missing: "Missing",
        number: "Number",
        pattern: "Pattern"
      },
      title: "Top historical numbers"
    }
  },
  shared: {
    positionLabel: "position"
  }
} as const;
