import { Heatmap, TimeSeriesChart } from "@/frontend/chart-primitives";
import { EmptyState, FilterToolbar, MetricCard } from "@/frontend/components";
import {
  Badge,
  Card,
  SectionHeading,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from "@/frontend/primitives";
import { apiGet } from "@/lib/api/http";
import { apiRoutes } from "@/lib/api/routes";
import { type AnalyticsReadModel, analyticsReadModelSchema } from "@/schema/app/analytics.schema";

const analyticsFallback = analyticsReadModelSchema.parse({
  digitStats: [],
  generatedAt: "2026-04-28T00:00:00.000Z",
  numberStats: [],
  patternSummaries: [],
  source: "mock",
  summary: {
    drawCount: 0,
    generatedAt: "2026-04-28T00:00:00.000Z"
  }
});

export async function AnalyticsPage() {
  const analytics = await getAnalyticsModel();
  const topDigits = analytics.digitStats.slice(0, 10);
  const topNumbers = analytics.numberStats.slice(0, 8);

  return (
    <main className="space-y-6">
      <section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
        <Card className="p-6 md:p-8">
          <p className="text-[11px] font-bold uppercase tracking-normal text-[var(--color-brand-outline)]">
            Analytics
          </p>
          <h1 className="mt-4 max-w-3xl text-4xl font-bold tracking-normal text-[var(--color-text-primary)]">
            Frequency, position, and recency signals
          </h1>
          <p className="mt-4 max-w-2xl text-base leading-7 text-[var(--color-text-secondary)]">
            Historical draw data is grouped into digit and number statistics for analysis. These
            signals describe past behavior only.
          </p>
        </Card>

        <Card className="p-6">
          <SectionHeading eyebrow="Data window" title="Current sample" />
          <div className="mt-5 grid gap-3">
            <MetricCard
              hint="Distinct draw records included in this analytics response."
              label="Draws"
              value={String(analytics.summary.drawCount)}
            />
            <MetricCard
              hint="Generated by API contract or fallback mock."
              label="Source"
              value={analytics.source}
            />
          </div>
        </Card>
      </section>

      <FilterToolbar
        filters={
          <>
            <MetricCard label="Digit groups" value={String(analytics.digitStats.length)} />
            <MetricCard label="Number groups" value={String(analytics.numberStats.length)} />
            <MetricCard label="Patterns" value={String(analytics.patternSummaries.length)} />
            <MetricCard
              label="Generated"
              value={new Date(analytics.generatedAt).toLocaleDateString("th-TH")}
            />
          </>
        }
        summary="Filters will be URL-backed in the next UI pass. This view currently uses the default analytics window contract."
      />

      {analytics.numberStats.length === 0 ? (
        <EmptyState
          description="Seed draw and prize records before enabling the production analytics view."
          title="No analytics records"
        />
      ) : null}

      <section className="grid gap-6 xl:grid-cols-2">
        <TimeSeriesChart
          points={topNumbers.map((stat) => ({
            id: `${stat.prizeType}-${stat.number}`,
            label: stat.number,
            value: stat.frequencyPercent
          }))}
          title="Top number frequency"
        />
        <Heatmap
          cells={topDigits.map((stat) => ({
            id: `${stat.prizeType}-${stat.position}-${stat.digit}`,
            label: stat.digit,
            value: stat.hitCount
          }))}
          title="Digit heatmap"
        />
      </section>

      <section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_420px]">
        <Card className="p-6">
          <SectionHeading eyebrow="Number stats" title="Top historical numbers" />
          <div className="mt-5 overflow-hidden rounded-none border border-[var(--color-border-soft)]">
            <Table>
              <TableHeader className="bg-[var(--color-bg-subtle)]">
                <TableRow className="border-b border-[var(--color-border-soft)] hover:bg-transparent">
                  <TableHead className="px-4 py-3 text-xs font-bold uppercase tracking-normal text-[var(--color-text-muted)]">
                    Number
                  </TableHead>
                  <TableHead className="px-4 py-3 text-xs font-bold uppercase tracking-normal text-[var(--color-text-muted)]">
                    Frequency
                  </TableHead>
                  <TableHead className="px-4 py-3 text-xs font-bold uppercase tracking-normal text-[var(--color-text-muted)]">
                    Missing
                  </TableHead>
                  <TableHead className="px-4 py-3 text-xs font-bold uppercase tracking-normal text-[var(--color-text-muted)]">
                    Pattern
                  </TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {topNumbers.map((stat) => (
                  <TableRow
                    className="border-b border-[var(--color-border-soft)] hover:bg-[var(--color-bg-subtle)]/50"
                    key={`${stat.prizeType}-${stat.number}`}
                  >
                    <TableCell className="px-4 py-3 font-mono text-lg font-semibold text-[var(--color-text-primary)]">
                      {stat.number}
                    </TableCell>
                    <TableCell className="px-4 py-3 text-[var(--color-text-secondary)]">
                      {stat.frequencyPercent}%
                    </TableCell>
                    <TableCell className="px-4 py-3 text-[var(--color-text-secondary)]">
                      {stat.missingDrawCount}
                    </TableCell>
                    <TableCell className="px-4 py-3">
                      <div className="flex flex-wrap gap-1.5">
                        {stat.patternFlags.map((flag) => (
                          <Badge key={`${stat.number}-${flag}`} variant="brand">
                            {flag}
                          </Badge>
                        ))}
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </Card>

        <Card className="p-6">
          <SectionHeading eyebrow="Digit stats" title="Position frequency" />
          <div className="mt-5 space-y-3">
            {topDigits.map((stat) => (
              <div
                className="flex items-center justify-between border-b border-[var(--color-border-soft)] pb-3"
                key={`${stat.prizeType}-${stat.position}-${stat.digit}`}
              >
                <div>
                  <p className="font-mono text-lg font-semibold text-[var(--color-text-primary)]">
                    {stat.digit}
                  </p>
                  <p className="text-xs text-[var(--color-text-muted)]">
                    {stat.prizeType} position {stat.position}
                  </p>
                </div>
                <Badge variant={stat.trendDirection === "up" ? "success" : "muted"}>
                  {stat.frequencyPercent}%
                </Badge>
              </div>
            ))}
          </div>
        </Card>
      </section>
    </main>
  );
}

async function getAnalyticsModel(): Promise<AnalyticsReadModel> {
  try {
    return await apiGet<AnalyticsReadModel>(apiRoutes.analytics, {
      cache: "no-store",
      schema: analyticsReadModelSchema
    });
  } catch {
    return analyticsFallback;
  }
}
